# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: corepack enable
      - run: pnpm i
      # Clone build cache repo
      - run: git clone https://github.com/penjj/turbo-build-cache.git ./node_modules/.cache/turbo
      # Build and write cache
      - run: pnpm build
      # Save cache to repo
      - run: cd ./node_modules/.cache/turbo && git commit -m "update cache" -a && git push -f