# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GPT: ${{ secrets.GPT }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: pnpm install
        run: |
          corepack enable
          pnpm i
      - name: Clone build cache repo
        run: git clone https://github.com/penjj/turbo-build-cache.git ./node_modules/.cache/turbo
      - name: Build and write cache
        run: pnpm build
      - name: Save cache to repo
        working-directory: ./node_modules/.cache/turbo
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'CI_ROBOT'
            git config --global user.email 'peng.j.1995@gmail.com'
            git remote set-url origin https://$GPT@github.com/penjj/turbo-build-cache.git
            git add .
            git commit -m "update cache"
            git push -f
          fi
         
